// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
function client(ctx) {
  const token = ctx.getToken();
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: token ? { headers: { Authorization: `Bearer ${token}` } } : {},
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search OGURA products",
  description: "Search live OGURA products by keyword, category, or price range. Returns a list of products with id, title, price, category, and description.",
  inputSchema: {
    query: z.string().trim().optional().describe("Keyword to match against product title or description."),
    category: z.string().trim().optional().describe("Category slug or name to filter by."),
    max_price: z.number().int().positive().optional().describe("Maximum price in INR."),
    limit: z.number().int().min(1).max(50).optional().describe("Max number of results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, max_price, limit }, ctx) => {
    const supabase = client(ctx);
    let q = supabase.from("products").select("id, title, price, category, short_description, description, images").eq("status", "live").limit(limit ?? 20);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    if (max_price) q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.23.8";
function client2(ctx) {
  const token = ctx.getToken();
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: token ? { headers: { Authorization: `Bearer ${token}` } } : {},
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get an OGURA product",
  description: "Fetch full details for a single OGURA product by its id.",
  inputSchema: {
    product_id: z2.string().uuid().describe("The product's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }, ctx) => {
    const { data, error } = await client2(ctx).from("products").select("*").eq("id", product_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.23.8";
function userClient(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my OGURA orders",
  description: "List the signed-in OGURA customer's own orders, most recent first. Requires authentication.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max number of orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "You must be signed in to view your orders." }],
        isError: true
      };
    }
    const { data, error } = await userClient(ctx).from("orders").select(
      "id, order_number, status, subtotal, shipping_fee, discount, total, tracking_id, created_at"
    ).eq("customer_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yudzgkrjsstqbfrrrrly";
var mcp_default = defineMcp({
  name: "ogura-mcp",
  title: "OGURA",
  version: "0.1.0",
  instructions: "Tools for the OGURA luxury fashion marketplace. Use search_products to browse the live catalog, get_product to fetch a specific product's details, and list_my_orders to view the signed-in customer's own orders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
